{
    "LogTailTest": {
        "tail_len": 60,
        "log_tail": "['[2019-02-08 11:09:31,780: INFO/MainProcess] sync with celery@workflow_worker', \"[2019-02-08 11:09:31,781: ERROR/MainProcess] Control command error: ConnectionResetError(104, 'Connection reset by peer')\", 'Traceback (most recent call last):', '  File \"/home/aver/lib/python3.5/site-packages/celery/worker/pidbox.py\", line 46, in on_message', '    self.node.handle_message(body, message)', '  File \"/home/aver/lib/python3.5/site-packages/kombu/pidbox.py\", line 129, in handle_message', '    return self.dispatch(**body)', '  File \"/home/aver/lib/python3.5/site-packages/kombu/pidbox.py\", line 112, in dispatch', '    ticket=ticket)', '  File \"/home/aver/lib/python3.5/site-packages/kombu/pidbox.py\", line 135, in reply', '    serializer=self.mailbox.serializer)', '  File \"/home/aver/lib/python3.5/site-packages/kombu/pidbox.py\", line 265, in _publish_reply', '    **opts', '  File \"/home/aver/lib/python3.5/site-packages/kombu/messaging.py\", line 181, in publish', '    exchange_name, declare,', '  File \"/home/aver/lib/python3.5/site-packages/kombu/messaging.py\", line 194, in _publish', '    [maybe_declare(entity) for entity in declare]', '  File \"/home/aver/lib/python3.5/site-packages/kombu/messaging.py\", line 194, in <listcomp>', '    [maybe_declare(entity) for entity in declare]', '  File \"/home/aver/lib/python3.5/site-packages/kombu/messaging.py\", line 102, in maybe_declare', '    return maybe_declare(entity, self.channel, retry, **retry_policy)', '  File \"/home/aver/lib/python3.5/site-packages/kombu/common.py\", line 129, in maybe_declare', '    return _maybe_declare(entity, declared, ident, channel, orig)', '  File \"/home/aver/lib/python3.5/site-packages/kombu/common.py\", line 135, in _maybe_declare', '    entity.declare(channel=channel)', '  File \"/home/aver/lib/python3.5/site-packages/kombu/entity.py\", line 185, in declare', '    nowait=nowait, passive=passive,', '  File \"/home/aver/lib/python3.5/site-packages/amqp/channel.py\", line 614, in exchange_declare', '    wait=None if nowait else spec.Exchange.DeclareOk,', '  File \"/home/aver/lib/python3.5/site-packages/amqp/abstract_channel.py\", line 50, in send_method', '    conn.frame_writer(1, self.channel_id, sig, args, content)', '  File \"/home/aver/lib/python3.5/site-packages/amqp/method_framing.py\", line 166, in write_frame', '    write(view[:offset])', '  File \"/home/aver/lib/python3.5/site-packages/amqp/transport.py\", line 275, in write', '    self._write(s)', 'ConnectionResetError: [Errno 104] Connection reset by peer', '', 'worker: Warm shutdown (MainProcess)', '[2019-02-08 11:57:16,002: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//', '[2019-02-08 11:57:16,046: INFO/MainProcess] mingle: searching for neighbors', '[2019-02-08 11:57:17,248: INFO/MainProcess] mingle: all alone', '[2019-02-08 11:57:17,264: INFO/MainProcess] celery@default_worker ready.', '', 'worker: Warm shutdown (MainProcess)', '[2019-02-08 12:27:09,812: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//', '[2019-02-08 12:27:09,838: INFO/MainProcess] mingle: searching for neighbors', '[2019-02-08 12:27:10,892: INFO/MainProcess] mingle: all alone', '[2019-02-08 12:27:10,925: INFO/MainProcess] celery@default_worker ready.', '', 'worker: Warm shutdown (MainProcess)', '[2019-02-08 14:42:01,324: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//', '[2019-02-08 14:42:01,358: INFO/MainProcess] mingle: searching for neighbors', '[2019-02-08 14:42:02,401: INFO/MainProcess] mingle: all alone', '[2019-02-08 14:42:02,419: INFO/MainProcess] celery@default_worker ready.', '', 'worker: Warm shutdown (MainProcess)', '[2019-02-08 14:48:47,832: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//', '[2019-02-08 14:48:47,864: INFO/MainProcess] mingle: searching for neighbors', '[2019-02-08 14:48:48,908: INFO/MainProcess] mingle: all alone', '[2019-02-08 14:48:48,922: INFO/MainProcess] celery@default_worker ready.']"
    }
}